### ISSUE TITLE
Question about the type of input file and reference sequences 

### ISSUE THREAD

**Issue by wlhCNU** [enovoa/EpiNano#1]
Hello，
      I am confused that must EpiNano software have both 'unmodified' and 'modified' sequences as input files to detect m6A RNA modifications ?  Does this mean that I can't detect native RNA m6A modifications in the case that the  'unmodified'  sequences were not available？
       Which reference fasta sequences should be used to RNA mapping,  genome reference or transcriptome reference ? 
        Are the modified RNA bases results  transcript isoform-specfic modification information or genome site-specfic modification information ?

**Comment by enovoa** [comment]
Hi, the current algorithm has been tested and benchmarked on synthetic sequences (which included both unmodified and m6A-modified sequences). Although the SVM does not need unmodified and modified sequences to predict m6A modifications, it does need them to train the algorithm. We are currently working on releasing an update and full benchmark of the software to run the predictions at a transcriptome-wide level.
