### ISSUE TITLE
minimap2 step: input and reference files

### ISSUE THREAD

**Issue by sdwien** [enovoa/EpiNano#11]
In the example command for minimap2, you use the output of NanoFilt instead of the U>T converted fastq, is that correct?
Also, I assume you use a transcriptome fasta as input for minimap2, right?
Thank you, best, Sophia

**Comment by Huanle** [comment]
@sdwien 
In the example, U>T conversiont was carried out before nanofilt, so converted fastqs were mapped with minimap2. And yes, a reference transcriptome should be used. Otherwise, a reference genome will also wokr if alternative splicing is 'very' rare.
