### ISSUE TITLE
per_read_var.stats.py script

### ISSUE THREAD

**Issue by sdwien** [enovoa/EpiNano#12]
I cannot find the per_read_var.stats.py script that is used in step #5 of your workflow. Is it supposed to be in the /scripts subfolder of your repository? Or has it been renamed?
Thanks and best, Sophia

**Comment by Huanle** [comment]
@sdwien Thanks for pointing that out. Yes, it's been renamed as 'per_read_var.py'. I will modifiy the example command.

**Comment by sdwien** [comment]
thank you! It works for me (up to this step at least...) now!

**Comment by s-t-calus** [comment]
Hello, I've just eye-balled through the results from per_site_var.py and per_read_var.py. Is it normal to have the same output from these two algorithms? Moreover, Step 7 uses "mod.ref.per_site.var.csv", name of that file is different to the output of step 6.
