### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by axgraf** [enovoa/EpiNano#16]
Hi, 
I just wanted to try the examples for running the SVM.py stated in the Readme but I encounter an error. According to the shebang python3 should be used. I tried running it with the python3.6 
`python3.6 EpiNano/scripts/main/SVM.py -a -t EpiNano/examples/svm_input/sample1.csv -p EpiNano/examples/svm_input/sample2.csv -cl 1-5 -mc 11 -o test `

The output is:
`
Commad:  EpiNano/scripts/main/SVM.py -a -t EpiNano/examples/svm_input/sample1.csv -p EpiNano/examples/svm_input/sample2.csv -cl 1-5 -mc 11 -o test
Colunms-used:  1-5 output:  test.q1.q2.q3.q4.q5.SVM
Traceback (most recent call last):
  File "EpiNano/scripts/main/SVM.py", line 118, in <module>
    X_train, _, y_train, _, indices_train, _ = train_test_split(X,Y.values.ravel(), indices, test_size=0, random_state= 100)
  File "/usr/local/lib64/python3.6/site-packages/sklearn/model_selection/_split.py", line 2100, in train_test_split
    default_test_size=0.25)
  File "/usr/local/lib64/python3.6/site-packages/sklearn/model_selection/_split.py", line 1734, in _validate_shuffle_split
    '(0, 1) range'.format(test_size, n_samples))
ValueError: test_size=0 should be either positive and smaller than the number of samples 19953 or a float in the (0, 1) range
`

Is there anything I can do to solve the issue?
Thank you 
Best Alex

**Comment by Huanle** [comment]
Hi @axgraf,
Sorry for my late reply.
I tried the command again and it worked.
according to the error message: the input data was not properly split into train and test sets.
I wonder if this is related to sklearn package.

Below is a list of packages i installed. Can you try install the same ones through a virtual environment and then let me know if it works?
Python 3.6.3 (default, Jun 26 2019, 11:48:56)
numpy.__version__ 1.17.2
pandas.__version__ 0.24.2
sklearn.__version__ 0.20.2
pickle.format_version 4.0

**Comment by jprunier-ulaval** [comment]
Hi,
I also tried to run the example files and didn't work either although I have all updated packages.
```
ValueError: test_size=0 should be either positive and smaller than the number of samples 19953 or a float in the (0, 1) range
```

**Comment by akesarwani** [comment]
Remove 3.6 from python command:

python EpiNano/scripts/main/SVM.py -a -t EpiNano/examples/svm_input/sample1.csv -p EpiNano/examples/svm_input/sample2.csv -cl 1-5 -mc 11 -o test

**Comment by enovoa** [comment]
Closing this issue as it seems to be solved. Please re-open if you still have any issues, thank you!

**Comment by shubhamias12** [comment]
getting error:


ValueError                                Traceback (most recent call last)
<ipython-input-8-98f0459729fc> in <module>
     20     ## Dataset
     21     path = "CVC-612/"
---> 22     (train_x, train_y), (valid_x, valid_y), (test_x, test_y) = load_data(path)
     23 
     24     ## Hyperparameters

/workspace/shubham/data.py in load_data(path, split)
     15     test_size = int(split * total_size)
     16 
---> 17     train_x, valid_x = train_test_split(images, test_size=valid_size, random_state=42)
     18     train_y, valid_y = train_test_split(masks, test_size=valid_size, random_state=42)
     19 

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py in train_test_split(test_size, train_size, random_state, shuffle, stratify, *arrays)
   2420 
   2421     n_samples = _num_samples(arrays[0])
-> 2422     n_train, n_test = _validate_shuffle_split(
   2423         n_samples, test_size, train_size, default_test_size=0.25
   2424     )

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py in _validate_shuffle_split(n_samples, test_size, train_size, default_test_size)
   2041         and (test_size <= 0 or test_size >= 1)
   2042     ):
-> 2043         raise ValueError(
   2044             "test_size={0} should be either positive and smaller"
   2045             " than the number of samples {1} or a float in the "

ValueError: test_size=0 should be either positive and smaller than the number of samples 0 or a float in the (0, 1) range

**Comment by Huanle** [comment]
Hi @shubhamias12 ,

can you open a new issue and provide the relevant command?
