### ISSUE TITLE
Detection of 2′-hydroxyl modifications in direct RNA-seq data

### ISSUE THREAD

**Issue by s-t-calus** [enovoa/EpiNano#17]
Hello, I would like to use your software for prediction of RNA's native structure, similar to SHAPE-MaP presented during London Calling 2019. Recently, generated two sets of data (SHAPE +ve and -ve), indexed files, aligned reads with minimap2 and processed with nanopolish eventalign. Results look good but your program seems to be such more advanced i.e. single base resolution. I believe there is a need to train a model for detection of SHAPE adducts binding at the 2′-hydroxyl position. Do you think EpiNano will be able to recognize modification on various bases or can identify certain/single base modification (e.g. 'A') only? I also would be interested to apply your program with per-read resolution as our RNA may have heterogenic tertiary structures. Do you have any idea when this update may be implemented into EpiNano?

Thank you very much for your help.

Regards
s-t-c

**Comment by enovoa** [comment]
Hello, we are in the process of benchmarking additional RNA modifications using EpiNano, as well as providing per-read resolution. Current release is only for predicting RNA modifications at per-site level (not per-read). Hopefully these issues will be tackled in future updates on EpiNano. Thanks, Eva

**Comment by s-t-calus** [comment]
Hello Eva, thank you for a quick response. Do you think EpiNano will be able to recognize modification on various bases (G, A, T and C) at the same time or can only identify single base modification (e.g. 'A') at once? The RNA from my protocol will have SHAPE adducts at various bases but same sites so, I was wondering is your algorithm applicable?
