### ISSUE TITLE
SVM features, sequencing depth and modification probability

### ISSUE THREAD

**Issue by robinycfang** [enovoa/EpiNano#24]
Hi Eva,

I am currently using Nanopore to sequence RNA from patients' samples and try to investigate RNA m6a methylation in cancers using Epinano. I have read the publication of Epinano on Nature
Communications...impressive work done! 

I have some questions while using Epinano, and hope you guys can share
some experience with me. I understand that the SVM performs best with
features of quality, mismatch and deletion at each base. There is a model
file (EpiNano/models/SVM100/model2.1-mis3.del3.q3.poly.dump). I assume
this dump file only considers the central base, and the order of features
is mismatch, deletion and quality? I have successfully used Epinano to
predict RNA methylation, but I have some concerns that there might be a
lot of false negatives. I only have ~1 M reads per sample, and I believe
sequencing depth can be a huge impact on the prediction. I am going to do
a QC on these results by filtering out bases with few supporting reads and
low probabilities (0.95 cut-off?). What's your recommendations on the
minimum depth and probability of the base to be consider as m6a
modifications? Do you have any other suggestions on QC of the
results? Many thanks!

**Comment by enovoa** [comment]
Hi @robinycfang thanks for your interest. 

Regarding your questions:

1. The SVM model includes in its name the features used.  mis3.del3.q3 means the middle position for these 3 features is used only.

**Comment by robinycfang** [comment]
Hi @enovoa ,

Thanks again for you answer! I have limited access to samples so couldn't perform multiple replicates and WT vs KO. Do you think if I use a stringent cut-off, something like 10 supporting reads and modification probability of 0.95, this might do the trick to reduce FPs?

**Comment by enovoa** [comment]
I would not recommend doing this, but we did not assess it this way. I still don't think this will make the trick as there are other phenomena that can lead to "errors", such as RNA structure, and systematic base-calling errors which you would see even if you would sequence a nude RNA using nanopore.

**Comment by robinycfang** [comment]
Thanks, appreciate the reply!

**Comment by vahidAK** [comment]
Hi @robinycfang ,
I am using EpiNano for a purpose similar to yours. I was wondering after finding modifications for the per-site file, which base in the kmer is prediction for?
For example, consider the following line:
TAAGA,124403220:124403221:124403222:124403223:124403224,chr10,1.0:1.0:1.0:1.0:1.0,16.0,8.0,5.0,3.0,5.0,0.0,0.0,0.0,1.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mod,-0.8762640257834018,0.7606523413528626,0.2393476586471375

This prediction is for all the As in the Kmer, or predictions are just for middle position base in case of mis3,del3,q3 sequence?
I have already made an issue for this while ago, but I did not get any answer yet and as I searched I only find this issue somehow similar to my problem and I thought you may now the answer.
Thanks,
Vahid.

**Comment by robinycfang** [comment]
> Hi @robinycfang ,
> I am using EpiNano for a purpose similar to yours. I was wondering after finding modifications for the per-site file, which base in the kmer is prediction for?
> For example, consider the following line:
> TAAGA,124403220:124403221:124403222:124403223:124403224,chr10,1.0:1.0:1.0:1.0:1.0,16.0,8.0,5.0,3.0,5.0,0.0,0.0,0.0,1.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mod,-0.8762640257834018,0.7606523413528626,0.2393476586471375
> 
> This prediction is for all the As in the Kmer, or predictions are just for middle position base in case of mis3,del3,q3 sequence?
> I have already made an issue for this while ago, but I did not get any answer yet and as I searched I only find this issue somehow similar to my problem and I thought you may now the answer.
> Thanks,
> Vahid.

hmmmm...it's a bit fuzzy for me...if I remember correctly, the results are always referring to the middle A. If you use a model with q1,q2,del3,q4,del5 for example, you consider a 5mer with an A in the center, and also consider the 4 bases (quals of 1, 2 and 4, deletion of 5 in this case) adjacent to the middle A, but again the prediction is for the middle A. Well, in the case of mis3,del3,q3, you only consider the mismatch, deletion and quality of the middle A, not involved with the surrounding bases.

**Comment by enovoa** [comment]
Hi @robinycfang and @vahidAK, the current SVM is trained to use mis3,del3,q3 as these features were the ones that gave best results. including additional features from neighbouring features improved the performance of the model, but it also led to over-fitting of the model (see figure 2 in manuscript). However, it is true that the neighbouring positions may sometimes be the ones affected by the modification. So in a specific kmer, chosing a different position might be the best choice, but globally, at least in the case of m6A, the middle position is the majority of cases the one that contains the information of the modification. Not sure if this answers your question(s)? Thanks, Eva
