### ISSUE TITLE
checking docs

### ISSUE THREAD

**Issue by DrOllyGomez** [enovoa/EpiNano#25]
Hiya. I'm just going through the documentation, prior to installing and trying out, just to get straight what's needed, following through the pipeline.
Can I just confirm that step 7 in the docs, instead of reading...

python2 slide_per_site_var.py mod.ref.per_site.var.csv > mod.per_site.var.sliding.win.csv
python2 slide_per_site_var.py unm.ref.per_site.var.csv > unm.per_site.var.sliding.win.csv

..should actually read....

python2 slide_per_site_var.py mod.per_site.var.csv > mod.per_site.var.sliding.win.csv
python2 slide_per_site_var.py unm..per_site.var.csv > unm.per_site.var.sliding.win.csv

I reckon so, otherwise I've missed something. many thanks

**Comment by Huanle** [comment]
Hi @DrOllyGomez ,
It seems it's a question about the naming of the input file, which is the output file of the last step.
You can feel free to name the file in your own style. 
BTW, I am going to release an updated version of epinano which will is slimmer. 
Thanks for using the pipeline.
