### ISSUE TITLE
Modification Status Column

### ISSUE THREAD

**Issue by mmingay** [enovoa/EpiNano#26]
Hi,

When trying to predict modification status using the pre-trained model on a direct RNA library if the modification status is not known what should one input as the required "modification status" column `-mc`?

**Comment by Huanle** [comment]
Hi @mmingay ,

If you do not have that information. You do not need to specify it. 
It can still make predicitons but it will not be able to evaluate prediciton accuracy given no prior knowledge of the modification status.
