### ISSUE TITLE
It seems that there is a small flaw in "per_site_var.py"

### ISSUE THREAD

**Issue by weir12** [enovoa/EpiNano#3]
Hi:
Thank you for your code.It is very useful.
But I found  a bug in 41th lines of ` per_site_var.py`:
`if (ary[-2] != ary[5]):`
instead of 
`if (ary[-2] != ary[4]):`

Because the 5th column of the Sam2Tsv output file is `read-base` instead of the 4th column.

**Comment by Huanle** [comment]
@weir12 ,
https://github.com/enovoa/EpiNano/blob/master/scripts/main/per_site_var.py#L40
1) I think you are referring to line 40 ?  https://github.com/enovoa/EpiNano/blob/master/scripts/main/per_site_var.py#L40
2) ary[4] is the 5th column since python uses 0-based indexing.

**Comment by weir12** [comment]
Oh,you are right.I will close it.Thanks!
