### ISSUE TITLE
The sequence of your cloned fragments downstream of T7 promoter

### ISSUE THREAD

**Issue by vahidAK** [enovoa/EpiNano#32]
Hi @Huanle,
In the manuscript, you have provided the link to the raw fast5 files for the cloned fragments you used to make reads for the development of your method. But, I could not find the reference (i.e. the sequence of fragments you cloned). I would appreciate it if you could kindly provide me the sequences of those fragments.

Many thanks,
Vahid.

**Comment by enovoa** [comment]
Hi @vahidAK, you can find the fasta sequences of the curlcakes as Supplementary File S1 of the  manuscript, which is open access. Thanks, Eva

**Comment by vahidAK** [comment]
Great! Thanks a lot @Huanle
