### ISSUE TITLE
SVM.py gives error

### ISSUE THREAD

**Issue by sem0036** [enovoa/EpiNano#36]
Command: ~/EpiNano/scripts/SVM.py -a -t mod.tsv.per.site.var.csv -p unm.tsv.per.site.var.csv -cl 1-5 -mc 11 -o test

gives the error message "IndexError: single positional indexer is out-of-bounds" and I'm unclear on how to fix this issue

**Comment by Huanle** [comment]
Hi @sem0036 ,
Are you using python3?
it seems you are training with only modified sample, min telling me why is that?
Normally the error mesage will include the line number of the script. Maybe you did not copy the complete error message. can you confirm?

**Comment by enovoa** [comment]
hi @sem0036 please let us know if using python3 solved the issue. thanks! Eva

**Comment by sem0036** [comment]
Even with python3 it still is giving me this error.

**Comment by enovoa** [comment]
Hi @sem0036 - have you tried using the data in the example folder?

**Comment by sem0036** [comment]
I've tried with the example data (my first question was the modified vs unmodified) and with my own data, both give me the same Index Error.

**Comment by Huanle** [comment]
Hi @sem0036, would you mind sending your data to me so that i can have a test and help to figure out what has been going 'wrong'?
Thanks.

**Comment by enovoa** [comment]
Huanle - i think @sem0036's problem is unrelated to the data, as she has tried with the fast5 in the repo. @sem0036 if you could provide a more descriptive explanation of your error (e.g. versions that you currently have in your environment etc) that would be the best to troubleshoot. Index errors in my experience are related to problems in python versions used. Best, Eva

**Comment by Huanle** [comment]
@sem0036, @enovoa, I only see the command using @sem0036 's own data but not the one with example inputs. 
```-
python3.6 scripts/SVM.py -a -t examples/svm_input/sample1.csv -p examples/svm_input/sample2.csv -cl 3 -mc 11 -o test
```
The above command with example inputs work on my machine. 
So, it would be nice if you can: 
1) send me the command you are using with example inputs;
2) let me know your python version, mine is python3.6, under which I coded SVM.py;
3) run *pip3 freeze* and double check if you have all requested versions of python modules installed ?

Thanks a lot.

**Comment by sem0036** [comment]
Thank you for all the quick responses, @enovoa was correct in that is was incomplete python installation!
