### ISSUE TITLE
Yeast: True positive m6A modified RRACH sites

### ISSUE THREAD

**Issue by akesarwani** [enovoa/EpiNano#38]
For the validation of m6A site prediction in yeast, you used 363 true positive sites. Would you be able to deposit this information on github. At least, I can't see that in supplemental file from the publication.

Thanks

**Comment by enovoa** [comment]
The positive sites were extracted from the work published by Schwartz et al, Cell 2014, as cited and described in the methods section of the paper. The final list comes from filtering using specific coverage thresholds, as explained in the methods section. This list will depend on which base-caller you used, which filtering you used, which mapping you used, etc. Therefore, it is not truly relevant. We do not currently have a "list" as such as we didn't keep such intermediary list as a separate file, we would have to re-generate it again.  I would suggest to start with the total number of original sites (a bit over 1,000) which can be obtained from the work of Schwartz et al. Thanks!
