### ISSUE TITLE
How to get the correct RNA modifications for reverse transcripts?

### ISSUE THREAD

**Issue by huiWyuan** [enovoa/EpiNano#39]
Hi,
I use the genome as mapping reference with the following options "-ax splice -uf -k14". Some reads will mapping to the reverse strand, what should I do for those reverse transcripts to get the right modification?
Thanks!

**Comment by Huanle** [comment]
@huiWyuan 
Epinano performs analysis at per-site level, i.e., with reads mapped both to forward and reverse strands, but it reports all motifs/kmers on forward strand.
You can intersect the coordinates of your interested motifs/sites from the reverse transcripts with Epinano results. 
Hope this answers your question.

**Comment by Huanle** [comment]
Hi @huiWyuan ,
Epinano 1.2 can take care of strandedness for you as long as you signify the type of reads mapping, i.e., mapping to reference genome or reference transcriptome. 
Please clone Epinano1.2 and give it a go.

**Comment by huiWyuan** [comment]
Thank you for your reply. I'll test with this new version.
