### ISSUE TITLE
Error encountered with trimming fastQ files

### ISSUE THREAD

**Issue by amy1847** [enovoa/EpiNano#4]
Hi,

I'm trying to trim the raw fastq with NanoFilt and am using Ubuntu, pip3 and python 3.6.8. When I enter the command, I receive this error: cat: invalid option -- 'q'. Any suggestions as to how to overcome this?

Thanks!

**Comment by Huanle** [comment]
It seems to me that NanoFilt is not in the current working directory.
you can use a soft link to NanoFilt or add its location to the environmental path after having it installed.
I can perhaps help more if you send me the complete command you used.

**Comment by amy1847** [comment]
Hi @Huanle ,

I have a few new user questions just about the code in general. I emailed elzedliu@gmail.com a few days ago. Is that the correct email address?

Thanks!

**Comment by Huanle** [comment]
Hi @amy1847 ,
Yes. the email address is correct.
But i haven't received any message from you. What is your email address?

Thanks!

**Comment by amy1847** [comment]
Hi @Huanle,

My email addtesss is adistiller@student.unimelb.edu.au.

If you search by that, you’ll find a few emails.

Thanks!
