### ISSUE TITLE
Epinano 1.1 Strand Information

### ISSUE THREAD

**Issue by akk01** [enovoa/EpiNano#41]
For `per_site_var.5mer.csv` or `tsv.per.site.var.csv`, how to find the correct strand. Can you add the corresponding read name and the strand it mapped to genome.

**Comment by enovoa** [comment]
Hi @akk01, this is in our to-do list. We had it in previous versions but not in the latest one. We will for sure include it in an updated version soon.

**Comment by akk01** [comment]
Thanks for your prompt response. Would you be able to suggest me any approach of  determining the strand at least for now while your are working on enhancement.

**Comment by Huanle** [comment]
hi @akk01 
If you are working on a simple genome, you can scan the reference for all motifs on both forward and backward strands and then intersect all kmer-locations with those locations in the feature table. 
I attached a python script for that purpose.

**Comment by enovoa** [comment]
Hi @akk01 , please let us know if Huanle's suggestion solved your issue. If yes, will close this issue. Thank you!
