### ISSUE TITLE
Current Intensity Extraction

### ISSUE THREAD

**Issue by akk01** [enovoa/EpiNano#44]
In the new release of epinano, did you remove the option to extract current intensity extraction for five positions of kmer. Having current intensity data is still useful in addition to quality, mismatch, deletion and insertions.

**Comment by enovoa** [comment]
Hi @akk01, yes we removed in EpiNano 1.1.
We expect to release sometime soon a new version that will have them.
For the moment, you can still use EpiNano 1.0 if you want to extract these features. Thanks for your input.

**Comment by laguda-1996** [comment]
![QQ截图20200418101717](https://user-images.githubusercontent.com/41985758/79625773-eb6dba80-815d-11ea-805f-2ab5861bc730.png)
Hello, I'm using epinano 1.0. But the script using python2 is not in your script library as shown in the figure.What should I do.？Thank you in advance for your reply

**Comment by Huanle** [comment]
Hi @akk01 ,
I attached the scripts you are looking for. 
But as i mentioned, these scripts do naive (and even wrong) matching between kmer and squiggles. 
I will release v1.2, which include resquiggling based on nanopolish eventalign very soon.
[1.0_squiggle_git_issue.tar.gz](https://github.com/enovoa/EpiNano/files/4994569/1.0_squiggle_git_issue.tar.gz)

**Comment by Huanle** [comment]
Hi @akk01 ,
Now Epinano_Current_intensity.sh can do the job for you.
