### ISSUE TITLE
SK1 Reference Genome

### ISSUE THREAD

**Issue by vahidAK** [enovoa/EpiNano#45]
Hi @Huanle and @tleonardi ,
Can you please provide me the SK1 strain reference genome you have used?
The ones I can find at SGD and NCBI for SK1 have about 500 scaffolds and they are not assembled to chromosomes.

Thanks,
Vahid.

**Comment by enovoa** [comment]
Hi @vahidAK, you can now find the SK1 reference fasta in the reference_fasta folder. Thanks, Eva
