### ISSUE TITLE
GFF for SK1 fasta

### ISSUE THREAD

**Issue by cathoderaymission** [enovoa/EpiNano#49]
I am unable to find the exact fasta sequence file for the SK1 strain you recently added. Can you provide the source? I would like to get the GFF file for the transcriptome. 

Thanks!

**Comment by cathoderaymission** [comment]
I found the genome under ftp://ftp.sanger.ac.uk/pub/users/dmc/yeast/latest/cere_assemblies.tgz
however the transcriptome contained in the GFF records goes over the bounds for the sequence lengths for things like the YIR023C-A gene in chromosome 9.

Did the epinano project use the sk1 genome you recently added under references or the transcriptome for alignment?

**Comment by Huanle** [comment]
Hi @cathoderaymission,

We used SK1 genome for alignment.

**Comment by Huanle** [comment]
> I found the genome under ftp://ftp.sanger.ac.uk/pub/users/dmc/yeast/latest/cere_assemblies.tgz
> however the transcriptome contained in the GFF records goes over the bounds for the sequence lengths for things like the YIR023C-A gene in chromosome 9.
> 
> Did the epinano project use the sk1 genome you recently added under references or the transcriptome for alignment?

You might want to try get the annotation of SK1 from https://software.broadinstitute.org/software/igv/Genomes
