### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ishaaq34** [enovoa/EpiNano#5]
How much coverage do we need for  a direct RNA  sequencing experiment that would be optimum for  identification of m6a sites ?

**Comment by enovoa** [comment]
It will depend on the expression levels of the gene, as well as on the stoichiometry of the modification at a given site. If the site is only modified at low levels and you have poor coverage, you won't be able to detect anything.  We have not benchmarked the optimum coverage needed, as in our cases we were using high coverage data from training/testing. I would recommend not going below 50reads coverage per site, but as mentioned, we have not done any type of benchmarking to determine this number.

**Comment by enovoa** [comment]
However, it is something that could be done as improvement as I agree that your question is relevant to apply the software to unknown scenarios. Thanks for your contribution

**Comment by ishaaq34** [comment]
Thanks for the response , 

We are interested in comparing the m6a topology of infected and control transcriptome of a animal through nanopore . What special things you would like to suggest ?

**Comment by ishaaq34** [comment]
As we know m6a is most prevalent modifications !!

**Comment by enovoa** [comment]
Detecting m6A modifications in animals using nanopore will likely require either the use of improved protocols to improve the throughput, the use of many flowcells (expensive), or the use of promethion direct RNA sequencing. So unless you have access to promethion sequencing, I think that it might be a bit early to move forward with such design, but I could be wrong. Best of luck!

**Comment by ishaaq34** [comment]
Thanks for your Response,

Lets us talk about only mRNAs not whole transcriptome
How many flow cells  will required to get modifications  of mRNA  identified   (per sample)

**Comment by enovoa** [comment]
Hi ishaaq, I believe that this type of question would be best that you would address to Nanopore using the community portal.  We cannot provide expertise on how many flowcells you will need for your specific biological questions or organisms. We are currently working on this with our own samples and cannot provide an answer for your specific experiment.
