### ISSUE TITLE
sam2tsv incompatibility issues

### ISSUE THREAD

**Issue by snajder-r** [enovoa/EpiNano#52]
This applies to EpiNano 1.1 (as 1.2 is not yet released).

There are two problems with sam2tsv right now:

* Apparently the latest commit to the jvarkit repository (af51aa30de9d8db076c6c4b6509c75f4cfc55af8 from Jul 13 2020) broke compatibility by changing the order of fields in the output tsv file. 
TSV_to_Variants_Freq.py3 expects the third column of the tsv file to be the chromosome. With the new sam2tsv version, the third column is mapping quality and the chromosome is found in the fourth column.
* The version used in EpiNano according to the Readme (a779a30d6af485d9cd669aa3752465132cf21eec) can no longer easily be installed, as its built script links to central.maven.org, which no longer exists. Perhaps there is an easy workaround, like changing a config file somewhere, but I didn't invest time in checking.

I am now trying to use sam2tsv 57fc476563ef8e1584e63d4fd5ec629961e0a45b. It seems to output the right format - here's to hoping there aren't any other changes that break compatibility.

Best,
Rene

**Comment by Huanle** [comment]
Hi @Rene,
Thanks for bringing this to my attention. 
I will modify the script so that it can recognize column names rather than numeric index.
Best,
Huanle

**Comment by Huanle** [comment]
Hi @snajder-r , i realised that the newer sam2tsv changed not only orders but also names of the columns. So i uploaded a older version to misc of Epinano V1.2.
