### ISSUE TITLE
What are the columns of ko_wt_combined.per_site_raw_feature.rrach.5mer.csv 

### ISSUE THREAD

**Issue by emanlee** [enovoa/EpiNano#54]
There is an example as follows.  What are the columns of ko_wt_combined.per_site_raw_feature.rrach.5mer.csv like? And, how to get such csv files from the output files of Step 1 and Step 2 in EpiNano 1.2 ?  Thanks a lot!

Example:
python $EPINANO_HOME/Epinano_Predict.py 
          --train **ko_wt_combined.per_site_raw_feature.rrach.5mer.csv**  
          --predict **ko_wt_combined.per_site_raw_feature.rrach.5mer.csv**  
          --accuracy_estimation --out_prefix train_and_test 
          --columns 8,13,23 --modification_status_column 26

**Comment by Huanle** [comment]
Hi @emanlee ,

There are some test data and example commands showing how to run it through.
Please refer to the follwoing links/locations:
https://github.com/enovoa/EpiNano/blob/master/test_data/make_predictions/
https://github.com/enovoa/EpiNano/blob/master/test_data/make_predictions/run.sh
