### ISSUE TITLE
Epinano_Variants tmp file Null end of lines

### ISSUE THREAD

**Issue by Celinet21** [enovoa/EpiNano#61]
a couple of my tmp files created by Epinano_Variants (e.g ... .per_site_var.5mer.tmp) have a final line (or 2 or 3) like:
`ACAGN,17488366-17488370,+2,Null`

or

`
GGTTN,46771258-46771262,-2,chr13,46771258,G,-,11,8.63636,7.00000,4.61761,0.00000,0.00000,0.00000
GGTTN,46771258-46771262,-1,chr13,46771259,G,-,12,9.66667,8.50000,6.89605,0.00000,0.00000,0.00000
GGTTN,46771258-46771262,+0,chr13,46771260,T,-,12,9.50000,7.50000,6.83740,0.00000,0.00000,0.00000
GGTTN,46771258-46771262,+1,chr13,46771261,T,-,12,9.50000,7.00000,6.46142,0.00000,0.00000,0.00000
GGTTN,46771258-46771262,+2,Null
`

Causing an index out of bound error at:

```
File "epinano_modules.py", line 869, in slide_per_site_var
    window = (ary[0], ary[1], ary[3], ary[6])		
IndexError: list index out of range
```

Only happens on usually ~2 chromosomes out of all.

**Comment by Huanle** [comment]
Hi @Celinet21 ,

Do you mind sending me your *per.site.var.csv file* so that i can relatively easily debug the relevant code?
Thanks.

**Comment by Celinet21** [comment]
Yeah sure, I'll use the email in the program. Let me know if you don't receive it, thanks!
