### ISSUE TITLE
syntax error occur during Epinano_variants command use

### ISSUE THREAD

**Issue by aman21392** [enovoa/EpiNano#62]
python /home/apps/EpiNano/Epinano_Variants.py -t 70 -R /Drive4/ncRNA_cdna/Homo_sapiens.GRCh38.cdna_all.ncrna.fa -b E6.bam -s /home/apps/EpiNano/misc/sam2tsv.jar --type t
  File "/home/apps/EpiNano/Epinano_Variants.py", line 54
    cmd_map = f"minimap2 -ax map-ont -t {ncpus} -k 5 --MD " \
                                                          ^
SyntaxError: invalid syntax

Please can you help me to solve this issue.
Thanks in advance

**Comment by Huanle** [comment]
Hi @aman21392 ,

Sorry for the late response. have you solved it?

**Comment by aman21392** [comment]
yes that problem solved.
Thanks

**Comment by yuxinPenny** [comment]
How did you solve this issue? I came up with this error too.

**Comment by aman21392** [comment]
you can use python3 instead of just python than your command.
