### ISSUE TITLE
sam file creation stuck

### ISSUE THREAD

**Issue by aman21392** [enovoa/EpiNano#63]
I used this command as you mentioned in the variants.py script but ----
minimap2 --MD -t 70 -k 5 -ax map-ont /Drive4/Homo_cdna.fa  /Drive8/combined_T.fastq >E6.sam

It running from 2 days and there is no increase in the size of the file -
[M::mm_idx_gen::7.289*1.39] collected minimizers
[M::mm_idx_gen::7.688*2.92] sorted minimizers
[M::main::7.721*2.91] loaded/built the index for 250156 target sequence(s)
[M::mm_mapopt_update::7.721*2.91] mid_occ = 1510760
[M::mm_idx_stat] kmer size: 5; skip: 10; is_hpc: 0; #seq: 250156
[M::mm_idx_stat::7.722*2.91] distinct minimizers: 396 (0.25% are singletons); average occurrences: 184315.192; average spacing: 5.407; total length: 394654324

It stuck here from 2days can you please suggest me what is the problem.
Thanks in advance

**Comment by aman21392** [comment]
I just want to know is there any logic to used --MD and -k 5 OR i can directly used default settings of minimap2 to create sam file.
Thanks in advance

**Comment by aman21392** [comment]
I just run these command and these will give bam file now. So is it fine. Thanks
minimap2 -ax map-ont -t 70 Homo_cdna.fa  /Drive4/combined_T.fastq | samtools view -@40 -hSb - | samtools sort -@ 40 -o E6.bam

**Comment by Huanle** [comment]
Hi @aman21392 ,

I am glad to know that you made minimap2 work.
`--MD` tag allows inferring indels without looking at reference sequences. 
`-k`, the minimizer, will change mapping sensitivity. Trying different minimizers, you will have different amount of reads mapped. 

The commands in the script was not run, they were there only for reference. The script takes bam and reference files as input. 

Best,

**Comment by weir12** [comment]
Hi @aman21392 
I had met the same problem as you, and then I solved it by  increasing` k` to 14 and selecting `splice` mode
