### ISSUE TITLE
Cannot download the code through the repo

### ISSUE THREAD

**Issue by yuxinPenny** [enovoa/EpiNano#66]
I cannot download the code for EpiNano1.2 to linux remote server through clone the repo: 

git clone git@github.com:enovoa/EpiNano.git

It returns: 
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Huanle** [comment]
Hi @yuxinPenny,
try 
```
git clone https://github.com/enovoa/EpiNano.git
```
