### ISSUE TITLE
Error: No module named "dask"

### ISSUE THREAD

**Issue by yuxinPenny** [enovoa/EpiNano#67]
$ python3 /home/share/yuxin/EpiNano/Epinano_Variants.py -n 6 -R /home/share/yuxin/DATA/hg19.fa -b /home/share/yuxin/DATA/Alignment.bam -s /home/share/yuxin/jvarkit/dist/sam2tsv.jar --type t

The above command returned error:

Traceback (most recent call last):
  File "/home/share/yuxin/EpiNano/Epinano_Variants.py", line 12, in <module>
    import dask.dataframe as dd 
ModuleNotFoundError: No module named 'dask'

What can I do to solve this issue?

**Comment by Huanle** [comment]
pip install pandas
pip install  dask==2.5.2
python -m pip install "dask[dataframe]
