### ISSUE TITLE
Explanation on the Epinano_Variants.py results

### ISSUE THREAD

**Issue by yuxinPenny** [enovoa/EpiNano#68]
Hi, I have successfully run the Epinano_Variants.py and got results. However, I found that in the output file, the X.ref column, which I expected to be the chromosome number (e.g. chr1), has values 0, 1, 2, ...6. Therefore, I cannot locate the each position. 

I wonder what is the correct value for this column? 

Below is my command:
python3 /home/share/yuxin/EpiNano/Epinano_Variants.py -n 2 -R /home/share/yuxin/DATA/hg19.fa -b /home/share/yuxin/Nanopore/DATA/HEK_WT_Alignment_sorted.bam -s /home/share/yuxin/jvarkit/dist/sam2tsv.jar --type g

**Comment by Huanle** [comment]
Hi @yuxinPenny ,
There should not be X.ref column in the output. Insteadm there should be `#Ref` column in per.site.csv file. 
Maybe you have imported it into R? 
Can you double check and let me know? Can you also `grep '>' hg19.fa` and confirm the sequecnes IDs?
