### ISSUE TITLE
Epinano_Variants.py - problem with multiprocessing?

### ISSUE THREAD

**Issue by nemitheasura** [enovoa/EpiNano#72]
Hi @enovoa , I encountered similar problem as mentioned in closed issues #55 and  #60 

I've tried multiple versions of python, packages/modules and multiple ways to create venvs and run the script. I constantly encounter the same problem, though I followed tips provided in both abovementioned issues. 

I also switched multiprocessing to multiprocess, as mentioned by Michael Dorner in this thread: https://stackoverflow.com/questions/41385708/multiprocessing-example-giving-attributeerror/42383397
(edited your script accordingly).

The error looks as follows:
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/software/EpiNano/1.2/lib/python3.6/site-packages/multiprocess/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/software/EpiNano/1.2/lib/python3.6/site-packages/multiprocess/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/software/EpiNano/1.2/Epinano_Variants.py", line 44, in split_tsv_for_per_site_var_freq
    head = next(tsv)
StopIteration

Below is my package list (one of the multiple configurations I've already tested - this was done in py3.6.7, 3.6.11 and 3.8.2):

Package            Version 
------------------ --------
attrs              20.3.0  
biopython          1.76    
cffi               1.14.3  
cloudpickle        1.6.0   
dask               2.5.2   
fsspec             0.8.4   
h5py               2.10.0  
importlib-metadata 3.1.0   
iniconfig          1.1.1   
Jinja2             2.11.2  
joblib             0.17.0  
locket             0.2.0   
MarkupSafe         1.1.1   
numpy              1.15.4  
packaging          20.4    
pandas             0.24.2  
partd              1.1.0   
pip                18.1    
pluggy             0.13.1  
py                 1.9.0   
pycparser          2.20    
pyparsing          2.4.7   
pysam              0.16.0.1
pytest             6.1.2   
python-dateutil    2.8.1   
pytz               2020.4  
PyYAML             5.3.1   
scikit-learn       0.20.2  
scipy              1.5.4   
setuptools         40.6.2  
six                1.15.0  
threadpoolctl      2.1.0   
toml               0.10.2  
toolz              0.11.1  
tzlocal            2.1     
zipp               3.4.0   

I would be grateful if you would like to help me solve this problem. 
Best,
N.

**Comment by Huanle** [comment]
Hi @nemitheasura ,
Can you confirm you are using the latest version and can you share with me your command?
Can you also `ls -l your_reference.fasta*` and show me the listed files?

Thanks a lot.

**Comment by nemitheasura** [comment]
Hi @Huanle, 

Thanks for your response. I am using EpiNano version 1.2 cloned from gh. 

1. In case of your training dataset:

Command:
Epinano_Variants.py -n 6 -R ref.fa -b wt.bam -s /usr/local/software/EpiNano/1.2/misc --type t

list of files:
-rw-r--r-- 1 nagumi users  183 lis 27 01:14 ref.dict
-rw-r--r-- 1 nagumi users 3460 lis 27 01:14 ref.fa
-rw-r--r-- 1 nagumi users   17 lis 27 01:14 ref.fa.fai

2. In case of my own dataset:
Command:
Epinano_Variants.py -n 6 -R ref_transcriptome_PK_based.fasta -b CKO1_transcriptome_map.bam -s /usr/local/software/EpiNano/1.2/misc --type t 

List of files:
-rw-r--r-- 1 nagumi users 13066080 lis 26 21:24 ref_transcriptome_PK_based.fasta
-rw-r--r-- 1 nagumi users  1747865 lis 26 21:34 ref_transcriptome_PK_based.fasta.dict
-rw-r--r-- 1 nagumi users   511840 lis 26 21:31 ref_transcriptome_PK_based.fasta.fai
-rw-r--r-- 1 nagumi users 43629546 lis 26 21:31 ref_transcriptome_PK_based.fasta.mmidx

In this case I have an additional minimap index for other purposes. 

As using my own data got me to end up with an error, I swithced to your test dataset. In each case, the error is the same. 

Oh, and I ran Epinano on two machines - here are my os details:

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"

NAME="Linux Mint"
VERSION="20 (Ulyana)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20"
VERSION_ID="20"

I also tried to run backup version (Epinano_Variants.bak) instead of the default one. Nothing changed, the same error occurred. 

Looking forward for your response. 
Best,
N.

**Comment by Huanle** [comment]
hi @nemitheasura ，
can you try  `-s /usr/local/software/EpiNano/1.2/misc/sam2tsv.jar` ?

**Comment by nemitheasura** [comment]
Hi, Huanle, thank you very much. I appreciate your help. 
Bless ya!
N.

**Comment by Huanle** [comment]
Hi @nemitheasura ,
`-f sum_err` tells the script to use `sum_err` as the feature for analysis. But it is not there. You should use whatever feature that is from your input file.
