### ISSUE TITLE
Epinano_Variants.py missing?

### ISSUE THREAD

**Issue by kxk302** [enovoa/EpiNano#73]
Hello, 

I just cloned Epinano and was reading the README.md file. In order to extract basecalling error features a python script called Epinano_Variants.py must be called. However, I could not find this script in the repo. Could you please advise how to proceed? Many Thanks!

Best,
-Kaivan

**Comment by Huanle** [comment]
my bad, i put it in the mis. but now you can clone it from the main folder.

**Comment by kxk302** [comment]
Thank you @Huanle!
