### ISSUE TITLE
output of sam2tsv not parsed correctly, perhaps?

### ISSUE THREAD

**Issue by EmanueleRaineri** [enovoa/EpiNano#76]
Hi,

thanks for your work on Epinano.

Not sure if it's a mistake on my side, but I seem to be getting incorrect chromosome names in the output of  `Epinano_Variants.py`.

I think you assume that the output header of
sam2tsv is
`#READ_NAME     FLAG    CHROM   READ_POS  BASE   QUAL  REF_POS REF  OP   STRAND`

whereas the real header is

`#Read-Name      Flag    MAPQ    CHROM   READ-POS` etc...

and so `MAPQ` is used instead of `CHROM` in the subsequent parsing?

but I'm not sure if this is the problem, or if there's something else.

**Comment by Huanle** [comment]
Hi @EmanueleRaineri ,

Probably you are using a different version of sam2tsv than the one used by epinano. 
Can you try with  `misc/sam2tsv.jar` ?

**Comment by EmanueleRaineri** [comment]
Makes sense. I didn't notice you were redistributing sam2tsv and installed a fresh copy. misc/sam2tsv has a different header, which i assume matches your code. At the moment I modified my local version of EpiNano so that it works with the sam2tsv I installed, but I will let you know if I roll back my changes to test with misc/sam2tsv.
Thanks for your reply.
