### ISSUE TITLE
#64 issues forward 

### ISSUE THREAD

**Issue by aman21392** [enovoa/EpiNano#77]
https://github.com/enovoa/EpiNano/issues/64
As you asked for the eventalign file and also I am sending the reads file among them.
[send.txt](https://github.com/enovoa/EpiNano/files/5733603/send.txt)
[send_fastq.txt](https://github.com/enovoa/EpiNano/files/5733604/send_fastq.txt)

There are 2 files in which the send.txt is an eventalign file and send.fastq.txt contains reads with the sequence present in the eventalign files.
Thanks in advance for looking at these files to sort out my issue.

**Comment by Huanle** [comment]
given that the last time we had already fixed your issues, i think you can use a small dataset to try and tell whether it is due to error or it simply needs lots of time to finish!
