### ISSUE TITLE
Could you provide us with a train file you had trained

### ISSUE THREAD

**Issue by iaunicorn** [enovoa/EpiNano#8]
hi, could you provide me with a train file which was trained for normal ONT-Met dataset  if I could not get my own train file？

**Comment by Huanle** [comment]
Hi @iaunicorn ,

you can download the trained models from [models](https://github.com/enovoa/EpiNano/tree/master/models )

**Comment by iaunicorn** [comment]
Hi, thanks for your reply. Are these models dataset suitable for all species?such as mouse or human? Are there somthing we need to concern about?
