### ISSUE TITLE
Epinano v1.2 Examples are not working

### ISSUE THREAD

**Issue by jjbblue** [enovoa/EpiNano#82]
Hi 
I just wanted to try the example for running the Epinano_predict.py stated in the Readme but I encounter an error.
According to the shebang python3 should be used.
I tried running it with the python3.6

![image](https://user-images.githubusercontent.com/29938706/107032354-04338380-67f7-11eb-8d0e-67c373e4e655.png)

The output is :
![image](https://user-images.githubusercontent.com/29938706/107032425-21685200-67f7-11eb-87e0-54b7a4c21be3.png)

Is there anything I can do to solve the issue?
Thank you 

Junbeom Jeon

**Comment by Huanle** [comment]
Hi @jjbblue ,

Can you run
`pip3.6 install EpinanoPredict==0.1.2` to install required pkgs and try again?

**Comment by jjbblue** [comment]
Thank you for answer. Thanks to that, it was solved.
