### ISSUE TITLE
Which pre-trained model should be used in Epinano_Predict.py (RNA m6A and m5C)

### ISSUE THREAD

**Issue by Stakaitis** [enovoa/EpiNano#84]
Hi,

1) In _EpiNano/models_ folder are currently 7 models, which ones should be used for RNA m6A prediction if one does not have a WT vs KO setup and only wants to check 1 sample for modifications?

2) Is it possible to use Epinano for RNA m5C detection without WT vs KO setup?

Thank You!
Rytis

**Comment by Huanle** [comment]
Hi Rytis,
> In EpiNano/models folder are currently 7 models, which ones should be used for RNA m6A prediction if one does not have a WT vs KO setup and only wants to check 1 sample for modifications?

You can use all those trained without *delta* features.

>Is it possible to use Epinano for RNA m5C detection without WT vs KO setup?

I have not tried predicting RNA m5C using SVM? But maybe you can give it a go by training some published data and use the trained models to make predictions. But without replicates, it will be hard to control for false positives.

Let me know if you need further information. 

Huanle
