### ISSUE TITLE
Epinano_Current.sh in genome mode throws an error

### ISSUE THREAD

**Issue by Zinksulfid** [enovoa/EpiNano#85]
Hello,

when I run Epinano_Current.sh in genome mode with
`.../Epinano_Current.sh -b .../file2.sorted.bam -r .../file.fastq -f .../file.fasta -d fast5_folder -t 8 -m g `
I get the following error:
`usage: create a table containing current intensity and duration information in 5mer windows
       [-h] --intensity_table INTENSITY_TABLE [--window WINDOW]
create a table containing current intensity and duration information in 5mer windows: error: unrecognized arguments: _events.collapsed/Intensity.collapsed.tsv`

Could it be that there are two spaces too much in Epinano_Current.sh in line 64 and 65, in which
`python ${src_d}/misc/Slide_Intensity.py --intensity_table ${evaln}.reverse _events.collapsed/Intensity.collapsed.tsv --window 5` should rather be
`... reverse_events.collapsed/Intensity.collapsed.tsv ...`and the same for the reverse strand events in l. 65?

This did solve the issue for me I suppose, maybe others will profit as well. Thank you for this amazing tool and the valuable documentation!

/Florian

**Comment by Huanle** [comment]
Hi @Florian,

Thanks a lot for pointing that out and apologies for getting back to you this late.
I tested it on a platform with Centos OS & Bourne shell but did not manage to reproduce the error.  So I wonder this could be OS/Shell specific. Can you give me more details about your OS and shell? 
Thanks a lot.

**Comment by florian** [comment]
Wrong @ mention :)
