### ISSUE TITLE
biological/technical replicates

### ISSUE THREAD

**Issue by LeilyR** [enovoa/EpiNano#87]
Hi, 

Thanks for the great tool. I am a newbie in the field of RNA modification and would apreciate your guidence on any recommended number of biological/technical replicates which your tool needs to to retrun the optimal output. (I have ko and wt of mouse)

Best,
Leily

**Comment by Huanle** [comment]
Hi @LeilyR,

Apologies for the late response. 

As in the case of differential gene expression analysis, there is a general consensus that increasing the number of samples will increase the statistical power of the relevant analyses. However, recommendations for the number of samples always vary according to different studies. 
The interplay between the number of replicates, reads alignment, sequencing depth, and other factors will further complicate the issue. 
So I do not have an idea of the ideal number of replicates for your study. 
That said, at the lower end of my recommendation, if the budget permits, it will be good to have 3 replicates, which is the median of the number of replicates used in DGE studies.

Huanle
