### ISSUE TITLE
polyA tails mapping

### ISSUE THREAD

**Issue by Cynthia0411** [enovoa/EpiNano#96]
When I tried to remap the data from SRP174366, I found that they are all perfectly mapped to the reference. However, based on the in vitro transcription process, there should be a polyA tail followed the "curlcake sequences". And as your trimming process is only 5 in 5' terminal and 3 in the 3' terminal, I was wondering where the polyA tails gone.  Thank you very much.

Best

**Comment by Huanle** [comment]
Hi @Cynthia0411 ,

PolyA tail sequences can not be basecalled at least for now. 
The ends-trimming was originally (for version1.0) done to remove low-qualities bases at ends. You can skip it now as it does not significantly affect mapping. 
Hope this helps. 
Let me know if you have any doubts.
