### ISSUE TITLE
Run EpiNano on single gene transcripts

### ISSUE THREAD

**Issue by Guoming-Gao** [enovoa/EpiNano#97]
We are interested in using the EpiNano developed in your group to analyze m6A modifications via RNA direct sequencing. The aim is to confirm the m6A modifications on RNAs transcribed from a single gene.

I followed the configurations and steps in the paper, _EpiNano: Detection of m6A RNA Modifications Using Oxford Nanopore Direct RNA Sequencing_, using a reference fasta file containing a single gene rather than a genome or transcriptome. 

I run:

`python ~/EpiNano/Epinano_Variants.py -n 6 -R ~/AS/m6a_construct_RNA.fa -b ~/AS/fastq_runid_ee1fefbf2a6d42535fdf1461936a093d220dca7d_0.bam -s /home/gmgao/jvarkit/dist/sam2tsv.jar --type g`

The following error came up when using Epinano_Variants.py:

`/home/gmgao/AS/m6a_construct_RNA.fa.fai needs to be created with samtools faidx`

I then used `samtools faidx m6a_construct_RNA.fa` to create the fai file and run Epinano_Variants.py again. However, a second error came up which I cannot solve:

`m6a_construct_RNA.fa.dict needs to be created using picard.jar CreateSequenceDictionary`

Note that I have installed all required software and packages in the specified versions using conda.

**Are there any specific preparation steps of the reference fasta file that should be done prior to being fed into EpiNano?**

**Comment by Guoming-Gao** [comment]
I have not tested it using the test data because I cannot find a way to use the test data on the starting step, which is Epinano_Variants.py. Can anyone help? Thanks a lot!

**Comment by Huanle** [comment]
Hi @Guoming-Gao ,

It reminds you to create a dictionary file for your reference. 
Please have a look at the [wiki ](https://github.com/enovoa/EpiNano/wiki/EpiNano-wiki). 
```java -jar picard.jar CreateSequenceDictionary R=transcriptome.fasta``` 

There are test data in the `test_data` folder.

**Comment by Guoming-Gao** [comment]
Thank you so much for pointing us to the wiki! That's very helpful! @Huanle 

Let me try running it today and see if the problem could be solved.
