### ISSUE TITLE
Problem with environment and docker container

### ISSUE THREAD

**Issue by F0nz0** [enovoa/EpiNano#98]
Hello,
I'm interested in using Epinano_Current script with the aim to retrieve raw signals of each read mapping to a specific genome's region.

In order to do that, I tried to create a new conda environment using the dependencies enlisted into this repository but conda, after several minutes of computation failed the installation saying that there are too many incompatibilities among dependecies packages indicated into .yml file. I changed a lot of diffent combinations of packages' versions, but the issue still remained.

Thus after that, I tried to use the docker file that you provided to build a Docker image and then launch Epinano_Current.sh via docker run. The building of the image was successffuly but in the end, launching this command: 

`$ docker run -it --rm --name epivar2 -v "$PWD/":/project/ epi12 bash /usr/local/bin/EpiNano/Epinano_Current.sh -b /project/data/ecoli_2kb_region/reads.bam -d /project/data/ecoli_2kb_region/fast5_files -r /projec
t/data/ecoli_2kb_region/reads.fasta -f /project/refs/ref.fa -m g -t 4`

I retrieved the following output and errors:

![image](https://user-images.githubusercontent.com/41163796/133892390-03cddc34-7455-415e-8769-388b6cfb4fc3.png)

What is it happening?
How can I fix these problems and how can I be able to use the whole Epinano package in a new conda environment or better as a docker container?

Thank you in advance.

**Comment by Huanle** [comment]
Hi @F0nz0 ,

This is because I ONLY install required packages for `Epinano_Variants`, which seems to be the most error-prone component based on the feedbacks. 
So i recommend you running the other parts without using docker.
Give it a go and let me know in case you run into any problems.

**Comment by F0nz0** [comment]
Hi @Huanle,

thank you for your answer!  I didn't figured out that the docker command was focused only on Epinano_Variants script. I will try to install other packages manually.  

Best Regards.
